#!/bin/sh
#-
# Copyright (c) 2021 Daniel Morante
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
#

set -e

progname=${0##*/}
conf_file=/usr/local/etc/apache24/httpd.conf

#
# Print an error message and exit.
#
error() {
	echo "$progname: $*" >&2
	exit 1
}

#
# Print a usage string and exit.
#
usage() {
	echo "usage: $progname [-f $conf_file] module_name" >&2
	exit 1
}

#
# Main program.
#
main () {
	while getopts :f: flag; do
		case "$flag" in
		f) conf_file=$OPTARG ;;
		\?) echo "Invalid option: -$OPTARG" >&2; return 1 ;;
		:) echo "Option -$OPTARG requires an argument." >&2; return 1 ;;
		esac
	done
	shift $(($OPTIND-1))

	module_name=$1

	if [ ! -f "$conf_file" ]; then echo -e \\n"Invalid configuration file."; return 2; fi
	if [ -z "$module_name" ]; then echo -e \\n"Module name not specified"; return 3; fi
	
	if [ "$progname" == "a2enmod" ]; then sed -i '' 's,^#\(LoadModule '${module_name}'.*$\),\1,g' $conf_file; fi
	if [ "$progname" == "a2dismod" ]; then sed -i '' 's,^\(LoadModule '${module_name}'.*$\),#\1,g' $conf_file; fi
}

main "$@"
