#!/bin/sh
#-
# Copyright (c) 2020 Daniel Morante
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
#

set -e

progname=${0##*/}

#
# Print an error message and exit.
#
error() {
	echo "$progname: $*" >&2
	exit 1
}

#
# Print a usage string and exit.
#
usage() {
	echo "usage: $progname [-hbfo]" >&2
	exit 1
}

#
# Main program.
#
main () {
	while getopts :f: flag; do
		case "$flag" in
		f) sc_config=$OPTARG ;;
		\?) echo "Invalid option: -$OPTARG" >&2; return 1 ;;
		:) echo "Option -$OPTARG requires an argument." >&2; return 1 ;;
		esac
	done
	shift $(($OPTIND-1))

	sc_value=$1
	sc_directive=`echo $sc_value | cut -d'=' -f1`

	if [ -z "$sc_value" ] || [ -z "$sc_directive" ] || [ -z "$sc_config" ]; then echo -e \\n"Mssing arguments"; return 1; fi

	if grep -sq $sc_directive $sc_config >&2; then
		sed -i '' -e "s#$sc_directive.*#$sc_value#" $sc_config
	else
		echo $sc_value >> $sc_config
	fi
}

main "$@"
